fields:
  autoplay:
    type: toggle
  loop:
    type: toggle
  api:
    type: toggle
  showinfo:
    type: toggle
  controls:
    type: toggle
  thumbnail_size:
    type: select
    options:
      large: Large
      medium: Medium
      small: Small
  key:
    type: text
